"""The attribution scope: 21 explicit keyword parameters, and why (D-03, ATTR-01).

:func:`attribution` is a context manager that sets Revenium attribution for the
spans created inside it. Phase 1 defines its signature and nothing else; the
``ContextVar`` that carries the values, the client-side cap validation, and the
concurrency behaviour are ATTR-01 through ATTR-11, in Phase 3.

**Why 21 named parameters instead of ``**kwargs`` or a TypedDict.** Revenium's
ingest silently *drops* an attribute key it does not recognise and silently
drops a value longer than its column cap — the trace still exports, the request
still returns 2xx, and no error appears on either side. A signature that accepts
arbitrary keys therefore converts ``subscriber_emial=`` into a permanent,
invisible billing-attribution loss discovered, if ever, at invoice time. Twenty-
one explicit keyword-only parameters make that same typo a ``TypeError`` at call
time and a red squiggle in the editor before that. This is the single place in
the SDK where a stricter signature buys a real class of failure rather than
tidiness, which is why V2-03's six additional attributes are deliberately a
future *signature change* rather than a dict key.

**Why keyword-only.** Twenty-one parameters that are almost all ``str | None``
would, if positional, let an off-by-one at the call site type-check perfectly
and attribute a customer's traffic to the wrong tenant. Keyword-only removes the
failure mode instead of documenting it.

The parameter names are not chosen; they are derived from
:data:`~revenium_mlflow.attributes.REVENIUM_ATTRIBUTE_KEYS` by one mechanical
rule — drop the ``revenium.`` prefix, replace dots with underscores — and
``tests/unit/test_attribution_signature.py`` recomputes that derivation rather
than hardcoding it, so the constants and this signature cannot drift apart.
"""

import contextlib
from collections.abc import Iterator

__all__ = ["attribution"]

_PHASE_3 = (
    "not implemented until Phase 3 (Attribution Context and Span Processor). "
    "Phase 1 publishes this signature so callers and type checkers can be written "
    "against it; entering the scope raises rather than yielding silently, because "
    "a no-op attribution scope would export spans that look attributed and are not."
)


@contextlib.contextmanager
def attribution(
    *,
    organization_name: str | None = None,
    product_name: str | None = None,
    subscription_id: str | None = None,
    subscriber_id: str | None = None,
    subscriber_email: str | None = None,
    agent_name: str | None = None,
    task_type: str | None = None,
    trace_type: str | None = None,
    trace_name: str | None = None,
    transaction_name: str | None = None,
    job_id: str | None = None,
    job_name: str | None = None,
    job_type: str | None = None,
    job_version: str | None = None,
    squad_id: str | None = None,
    squad_name: str | None = None,
    squad_role: str | None = None,
    operation_subtype: str | None = None,
    retry_number: int | None = None,
    request_stream: bool | None = None,
    middleware_source: str | None = None,
) -> Iterator[None]:
    """Set Revenium attribution for every span created within this scope.

    Every parameter defaults to ``None`` and every parameter is optional:
    attribution is additive, and supplying one key must never require supplying
    the other twenty. A ``None`` value means "say nothing about this key",
    which is distinct from saying it is empty.

    Args:
        organization_name: The Revenium organization the traffic is billed to.
        product_name: The product the traffic is attributed to.
        subscription_id: The subscription the traffic is rated under.
        subscriber_id: The end subscriber the traffic is attributed to.
        subscriber_email: The subscriber's email. Personal data — Phase 3
            redacts it from logs and exception text.
        agent_name: The agent that issued the call.
        task_type: The class of task being performed.
        trace_type: The class of trace.
        trace_name: The human-readable trace name.
        transaction_name: The logical transaction the call belongs to.
        job_id: The externally supplied agentic job identifier that job
            outcomes correlate on (JOB-01). Generated by the caller, never here.
        job_name: The job's human-readable name.
        job_type: The class of job.
        job_version: The job's version.
        squad_id: The squad the agent belongs to.
        squad_name: The squad's human-readable name.
        squad_role: The agent's role within the squad.
        operation_subtype: A refinement of the operation being metered.
        retry_number: Which retry attempt this call is.
        request_stream: Whether the request was streamed.
        middleware_source: Which Revenium middleware produced the telemetry.
            This SDK's value is ``mlflow`` (ATTR-08, Phase 3).

    Yields:
        Nothing. The scope is the value.

    Raises:
        NotImplementedError: On entry, in Phase 1. Constructing the context
            manager is free — the generator body does not run until ``__enter__``
            — so a caller can build one and a type checker can check one without
            reaching unimplemented code.
    """
    raise NotImplementedError(f"attribution() is {_PHASE_3}")
    # Unreachable, and deliberately kept: the ``yield`` is what makes this a
    # generator, which is what makes the ``@contextmanager`` decorator produce a
    # context manager whose construction is free and whose *entry* raises. The
    # narrow ignore is preferred over restructuring, because every alternative
    # that satisfies ``warn_unreachable`` (a helper that always raises but is
    # annotated as returning) hides the raise from the type checker instead.
    yield  # type: ignore[unreachable]
