"""The attribution scope: 21 explicit keyword parameters, and why (D-03, ATTR-01).

:func:`attribution` is a context manager that sets Revenium attribution for the
spans created inside it. Phase 1 published the signature; plan 03-01 filled in
the body. The ``ContextVar`` the values live in belongs to
:mod:`revenium_mlflow.tracing._scope`, which is the single module allowed to
declare one, and it is read back by
:class:`~revenium_mlflow.tracing.processor.ReveniumAttributionSpanProcessor` in
``on_start``. The client-side cap validation (ATTR-09) is still ahead, in plan
03-04.

**Why 21 named parameters instead of ``**kwargs`` or a TypedDict.** Revenium's
ingest silently *drops* an attribute key it does not recognise and silently
drops a value longer than its column cap — the trace still exports, the request
still returns 2xx, and no error appears on either side. A signature that accepts
arbitrary keys therefore converts ``subscriber_emial=`` into a permanent,
invisible billing-attribution loss discovered, if ever, at invoice time. Twenty-
one explicit keyword-only parameters make that same typo a ``TypeError`` at call
time and a red squiggle in the editor before that. This is the single place in
the SDK where a stricter signature buys a real class of failure rather than
tidiness, which is why V2-03's six additional attributes are deliberately a
future *signature change* rather than a dict key.

**Why keyword-only.** Twenty-one parameters that are almost all ``str | None``
would, if positional, let an off-by-one at the call site type-check perfectly
and attribute a customer's traffic to the wrong tenant. Keyword-only removes the
failure mode instead of documenting it.

The parameter names are not chosen; they are derived from
:data:`~revenium_mlflow.attributes.REVENIUM_ATTRIBUTE_KEYS` by one mechanical
rule — drop the ``revenium.`` prefix, replace dots with underscores — and
``tests/unit/test_attribution_signature.py`` recomputes that derivation rather
than hardcoding it, so the constants and this signature cannot drift apart.
"""

import contextlib
from collections.abc import Iterator

from . import _scope

__all__ = ["attribution"]


@contextlib.contextmanager
def attribution(
    *,
    organization_name: str | None = None,
    product_name: str | None = None,
    subscription_id: str | None = None,
    subscriber_id: str | None = None,
    subscriber_email: str | None = None,
    agent_name: str | None = None,
    task_type: str | None = None,
    trace_type: str | None = None,
    trace_name: str | None = None,
    transaction_name: str | None = None,
    job_id: str | None = None,
    job_name: str | None = None,
    job_type: str | None = None,
    job_version: str | None = None,
    squad_id: str | None = None,
    squad_name: str | None = None,
    squad_role: str | None = None,
    operation_subtype: str | None = None,
    retry_number: int | None = None,
    request_stream: bool | None = None,
    middleware_source: str | None = None,
) -> Iterator[None]:
    """Set Revenium attribution for every span created within this scope.

    Every parameter defaults to ``None`` and every parameter is optional:
    attribution is additive, and supplying one key must never require supplying
    the other twenty. A ``None`` value means "say nothing about this key",
    which is distinct from saying it is empty.

    Args:
        organization_name: The Revenium organization the traffic is billed to.
        product_name: The product the traffic is attributed to.
        subscription_id: The subscription the traffic is rated under.
        subscriber_id: The end subscriber the traffic is attributed to.
        subscriber_email: The subscriber's email. Personal data — Phase 3
            redacts it from logs and exception text.
        agent_name: The agent that issued the call.
        task_type: The class of task being performed.
        trace_type: The class of trace.
        trace_name: The human-readable trace name.
        transaction_name: The logical transaction the call belongs to.
        job_id: The externally supplied agentic job identifier that job
            outcomes correlate on (JOB-01). Generated by the caller, never here.
        job_name: The job's human-readable name.
        job_type: The class of job.
        job_version: The job's version.
        squad_id: The squad the agent belongs to.
        squad_name: The squad's human-readable name.
        squad_role: The agent's role within the squad.
        operation_subtype: A refinement of the operation being metered.
        retry_number: Which retry attempt this call is.
        request_stream: Whether the request was streamed.
        middleware_source: Which Revenium middleware produced the telemetry.
            The one parameter with a default *value* rather than merely a
            default of ``None``: a span stamped inside this scope carries
            ``revenium.middleware.source = "mlflow"`` unless you say otherwise
            (ATTR-08). The default is applied where the snapshot becomes span
            attributes, not here, so the published signature keeps its uniform
            ``None`` and ``None`` keeps meaning "say nothing" for this parameter
            as for the other twenty. **The default fills a missing key inside an
            active scope; it does not create one** — a span created outside every
            ``attribution()`` scope carries no ``revenium.*`` key at all,
            including this one, because a bare ``middleware.source`` would claim
            Revenium produced telemetry nobody attributed.

    Yields:
        Nothing. The scope is the value.

    **The scope is restored on the way out however the body ends, and that is
    what the ``finally`` is for (ATTR-04, T-03-02).** A scope that restored only
    on the normal path would leave a failed request's attribution installed for
    whatever ran next on the same task or worker thread, which on a reused worker
    means one customer's traffic billed to another — a leak that grows quieter
    the more reliable the surrounding code is. The caller's exception propagates
    unchanged, as the same object: nothing here catches it, and nothing here
    raises an exception of its own that would replace it and take its stack.

    **A nested scope merges over the enclosing one rather than replacing it**, so
    an inner ``attribution(product_name=...)`` keeps the outer scope's subscriber.
    The merge is copy-on-write — see :mod:`revenium_mlflow.tracing._scope` for why
    mutating the enclosing snapshot in place would be a cross-tenant failure
    rather than a lost write.
    """
    token = _scope.enter(
        {
            "organization_name": organization_name,
            "product_name": product_name,
            "subscription_id": subscription_id,
            "subscriber_id": subscriber_id,
            "subscriber_email": subscriber_email,
            "agent_name": agent_name,
            "task_type": task_type,
            "trace_type": trace_type,
            "trace_name": trace_name,
            "transaction_name": transaction_name,
            "job_id": job_id,
            "job_name": job_name,
            "job_type": job_type,
            "job_version": job_version,
            "squad_id": squad_id,
            "squad_name": squad_name,
            "squad_role": squad_role,
            "operation_subtype": operation_subtype,
            "retry_number": retry_number,
            "request_stream": request_stream,
            "middleware_source": middleware_source,
        }
    )
    try:
        yield
    finally:
        _scope.leave(token)
