"""ATTR-07 and ATTR-08: all 21 keys reach the span, and ``middleware.source`` defaults.

**Every call this module makes is built from ``REVENIUM_ATTRIBUTE_KEYS``, never
typed out.** A test that hand-writes twenty keyword arguments passes while
covering twenty, and the twenty-first parameter — whichever one the author's eye
skipped — accepts a value and discards it with no error on either side. That is
the exact failure ``attributes.py`` exists to prevent and the reason its
constant-naming rule is described there as load-bearing rather than cosmetic. So
the payload here is generated by applying the same mechanical rule the
implementation applies (drop ``revenium.``, dots to underscores), and the
expectations are generated by inverting it. If a twenty-second key is added to
the constants tuple and nothing else changes, these tests go red.

**Membership is asserted together with count.** A membership-only assertion —
"the span carries every key I supplied" — is satisfied by a processor that also
writes keys nobody asked for, which is the shape of an attribution leak rather
than an attribution drop. Both directions are checked: the collected span's
``revenium.*`` subset is compared for *equality* against the whole expected
mapping.

**Assertions are on the span the exporter collected**, through
``tests/fixtures/processors.py``, never on the live span object the test still
holds — see that module's docstring for why the live-span assertion passes even
when the value never survived to export.

Nothing here imports MLflow. The mechanism under test is the ContextVar, the
processor, and OpenTelemetry's attribute store.
"""

import pytest

from revenium_mlflow.attributes import (
    REVENIUM_ATTRIBUTE_KEYS,
    REVENIUM_MIDDLEWARE_SOURCE,
    REVENIUM_PRODUCT_NAME,
    REVENIUM_REQUEST_STREAM,
    REVENIUM_RETRY_NUMBER,
    REVENIUM_SUBSCRIBER_ID,
)
from revenium_mlflow.tracing import _scope, attribution
from tests.fixtures.processors import build_collecting_tracer, revenium_attributes

pytestmark = pytest.mark.unit

#: The prefix stripped to turn a key into a parameter name. The one string
#: literal in this module that names part of the wire format, and it is a prefix
#: rather than a key — the twenty-one keys themselves are only ever reached
#: through the imported constants.
_KEY_PREFIX = "revenium."

#: The two parameters that are not ``str``. Held as constants rather than as
#: string literals so a rename of either parameter fails at import rather than
#: silently dropping it out of the type assertions below.
_RETRY_NUMBER_VALUE = 7
_REQUEST_STREAM_VALUE = True


def _parameter_name(key: str) -> str:
    """The ``attribution()`` parameter name for a ``revenium.*`` key.

    Args:
        key: A member of :data:`REVENIUM_ATTRIBUTE_KEYS`.

    Returns:
        The parameter name, by the one mechanical rule ``attributes.py``
        documents and ``_scope.PARAMETER_TO_ATTRIBUTE_KEY`` applies: drop the
        ``revenium.`` prefix, replace dots with underscores.

    This is recomputed here rather than imported from ``_scope`` on purpose. A
    test that read the implementation's own table would agree with it by
    construction and would still pass if that table were built from a typo'd
    rule; recomputing the rule from the constants is what makes disagreement
    possible.
    """
    return key.removeprefix(_KEY_PREFIX).replace(".", "_")


def _every_parameter_with_a_distinct_value() -> dict[str, str | int | bool]:
    """One value per parameter, no two alike.

    Returns:
        A keyword payload for :func:`attribution` covering all 21 parameters.
        Each ``str`` value embeds its own parameter name, so a resolution that
        swapped two keys produces a failure naming both rather than a failure
        that reads as a single missing key. ``retry_number`` and
        ``request_stream`` carry an ``int`` and a ``bool`` because those are
        their declared types and the point of
        :func:`test_retry_number_and_request_stream_reach_the_span_in_their_declared_types`
        is that they arrive that way.
    """
    payload: dict[str, str | int | bool] = {}
    for key in REVENIUM_ATTRIBUTE_KEYS:
        name = _parameter_name(key)
        if key == REVENIUM_RETRY_NUMBER:
            payload[name] = _RETRY_NUMBER_VALUE
        elif key == REVENIUM_REQUEST_STREAM:
            payload[name] = _REQUEST_STREAM_VALUE
        else:
            payload[name] = f"value-for-{name}"
    return payload


def _expected_attributes(payload: dict[str, str | int | bool]) -> dict[str, str | int | bool]:
    """The ``revenium.*`` mapping ``payload`` should produce on a stamped span.

    Args:
        payload: Keyword arguments as handed to :func:`attribution`.

    Returns:
        The same values, re-keyed by wire key through the inverse of
        :func:`_parameter_name`. Built by inverting the rule rather than by
        reading ``_scope.PARAMETER_TO_ATTRIBUTE_KEY``, for the reason
        :func:`_parameter_name` records.
    """
    return {key: payload[_parameter_name(key)] for key in REVENIUM_ATTRIBUTE_KEYS}


# --- The resolution itself, before any span is involved --------------------


def test_the_constants_and_the_parameters_are_the_same_twenty_one() -> None:
    """The payload builder covers everything, so the tests below cannot cover twenty.

    Every assertion in this module is generated from
    :data:`REVENIUM_ATTRIBUTE_KEYS`. That generation is only trustworthy if the
    tuple is the whole set, so the count is pinned here rather than assumed.
    """
    payload = _every_parameter_with_a_distinct_value()
    assert len(REVENIUM_ATTRIBUTE_KEYS) == 21
    assert len(payload) == 21
    assert len(set(payload.values())) == 21, "values must be distinct or a key swap hides"


def test_all_twenty_one_parameters_resolve_to_their_own_key() -> None:
    """ATTR-07 at the resolution layer: 21 in, 21 out, each to the right key.

    Asserted as an equality against the whole expected mapping, so a resolution
    that dropped one key fails and a resolution that invented one fails too.
    """
    payload = _every_parameter_with_a_distinct_value()
    with attribution(**payload):  # type: ignore[arg-type]
        resolved = _scope.resolve_attributes(_scope.current())

    assert resolved == _expected_attributes(payload)
    assert len(resolved) == 21


def test_a_parameter_left_at_none_produces_no_key_at_all() -> None:
    """``None`` means silence, and silence is the absence of a key.

    Revenium's ingest cannot distinguish "the caller said nothing" from "the
    caller said empty" — both arrive as a column with no useful value — so
    stamping an empty string for an unsupplied parameter would assert a fact the
    caller never made, permanently and invisibly. The distinction is checked in
    both halves: the supplied key is present, and the unsupplied one is absent
    rather than present-and-empty.
    """
    with attribution(subscriber_id="s-1"):
        resolved = _scope.resolve_attributes(_scope.current())

    assert resolved[REVENIUM_SUBSCRIBER_ID] == "s-1"
    assert REVENIUM_PRODUCT_NAME not in resolved
    assert "" not in resolved.values()


def test_the_resolution_invents_no_key_outside_the_constants() -> None:
    """Nothing reaches a span that is not a published ATTR-07 key.

    The complement of the drop check. A resolution that mistyped one key would
    satisfy "21 keys resolved" while writing ``revenium.subscriber.idd``, which
    the backend discards in silence.
    """
    payload = _every_parameter_with_a_distinct_value()
    with attribution(**payload):  # type: ignore[arg-type]
        resolved = _scope.resolve_attributes(_scope.current())

    assert set(resolved) <= set(REVENIUM_ATTRIBUTE_KEYS)


# --- The same 21 keys, on the span an exporter collected -------------------


def test_all_twenty_one_keys_reach_a_collected_span_with_the_values_supplied() -> None:
    """ATTR-07 end to end: scope, processor, exporter, and an equality assertion.

    The span is created with ``gen_ai.operation.name="chat"`` so it is an
    eligible LLM span under the ``declared-only`` stamp-time rule rather than an
    undecided one — the shape the requirement is written about.
    """
    payload = _every_parameter_with_a_distinct_value()
    tracer, exporter = build_collecting_tracer()
    with attribution(**payload):  # type: ignore[arg-type]
        tracer.start_span("chat", attributes={"gen_ai.operation.name": "chat"}).end()

    (collected,) = exporter.get_finished_spans()
    assert revenium_attributes(collected) == _expected_attributes(payload)
    assert len(revenium_attributes(collected)) == 21


def test_retry_number_and_request_stream_reach_the_span_in_their_declared_types() -> None:
    """``int`` stays ``int`` and ``bool`` stays ``bool`` — no stringification.

    OpenTelemetry attribute values are natively typed for both, and Phase 2
    already established that a numeric telemetry value must arrive as a number
    rather than as its decimal spelling (SEM-04). Neither key appears in
    ``ATTRIBUTE_CAPS``, which is consistent with neither being a string column on
    the backend. Stamping ``retry_number`` as ``"1"`` would repeat, on the
    attribution half of the SDK, the exact defect ``mlflow.tracing.configure``
    was rejected for: values arriving JSON-encoded and being dropped or
    mis-stored.

    ``isinstance(value, int)`` alone would be satisfied by ``True``, since
    ``bool`` is a subclass of ``int``, so the retry assertion excludes ``bool``
    explicitly.
    """
    payload = _every_parameter_with_a_distinct_value()
    tracer, exporter = build_collecting_tracer()
    with attribution(**payload):  # type: ignore[arg-type]
        tracer.start_span("chat", attributes={"gen_ai.operation.name": "chat"}).end()

    (collected,) = exporter.get_finished_spans()
    stamped = revenium_attributes(collected)

    retry = stamped[REVENIUM_RETRY_NUMBER]
    assert isinstance(retry, int) and not isinstance(retry, bool)
    assert retry == _RETRY_NUMBER_VALUE

    stream = stamped[REVENIUM_REQUEST_STREAM]
    assert isinstance(stream, bool)
    assert stream is _REQUEST_STREAM_VALUE


def test_a_scope_supplying_one_parameter_stamps_that_key_and_no_other() -> None:
    """The negative control: the other twenty do not arrive as empty values.

    Without this, every assertion above would pass equally well against an
    implementation that wrote all 21 keys always, filling the unsupplied ones
    with ``""``. That implementation is worse than the drop it replaces: an empty
    string is a value the backend stores, so it would overwrite nothing with
    something and look like real attribution.

    ``middleware.source`` is expected here because it is defaulted (ATTR-08); see
    :func:`test_middleware_source_defaults_to_mlflow_when_the_caller_supplied_none`.
    Two keys, and the count is asserted, so the default cannot drag the other
    nineteen along with it.
    """
    tracer, exporter = build_collecting_tracer()
    with attribution(subscriber_id="s-1"):
        tracer.start_span("chat", attributes={"gen_ai.operation.name": "chat"}).end()

    (collected,) = exporter.get_finished_spans()
    stamped = revenium_attributes(collected)
    assert stamped == {
        REVENIUM_SUBSCRIBER_ID: "s-1",
        REVENIUM_MIDDLEWARE_SOURCE: "mlflow",
    }
    assert len(stamped) == 2


# --- ATTR-08: the middleware.source default --------------------------------


def test_middleware_source_defaults_to_mlflow_when_the_caller_supplied_none() -> None:
    """ATTR-08. The literal is written out here, once, deliberately.

    Every other expectation in this module is derived. This one cannot be: the
    *value* ``mlflow`` is the fact under test, and deriving it from the
    implementation's own constant would make the assertion agree with whatever
    the implementation happens to say.
    """
    tracer, exporter = build_collecting_tracer()
    with attribution(subscriber_id="s-1"):
        tracer.start_span("chat", attributes={"gen_ai.operation.name": "chat"}).end()

    (collected,) = exporter.get_finished_spans()
    assert revenium_attributes(collected)[REVENIUM_MIDDLEWARE_SOURCE] == "mlflow"


def test_an_explicit_middleware_source_is_not_overwritten_by_the_default() -> None:
    """A default that won over the caller would be a default nobody could turn off.

    The value matters beyond configurability: ``revenium.middleware.source`` is
    what tells Revenium which middleware produced a record, so a default that
    overrode the caller would make every record emitted through a wrapping
    integration claim to have come from this SDK.
    """
    tracer, exporter = build_collecting_tracer()
    with attribution(subscriber_id="s-1", middleware_source="custom"):
        tracer.start_span("chat", attributes={"gen_ai.operation.name": "chat"}).end()

    (collected,) = exporter.get_finished_spans()
    assert revenium_attributes(collected)[REVENIUM_MIDDLEWARE_SOURCE] == "custom"


def test_a_span_outside_every_scope_carries_no_middleware_source() -> None:
    """The default fills a missing key inside an active scope; it does not create one.

    A bare ``revenium.middleware.source`` on an otherwise unattributed span would
    assert Revenium provenance for traffic nobody attributed — spoofing the one
    field that identifies the producer of a billing record (T-03-06). This
    processor runs for *every* span in the host process, including in processes
    that never call :func:`attribution` at all, so the wrong boundary here would
    mark the customer's entire trace store as Revenium-sourced.
    """
    tracer, exporter = build_collecting_tracer()
    tracer.start_span("chat", attributes={"gen_ai.operation.name": "chat"}).end()

    (collected,) = exporter.get_finished_spans()
    assert revenium_attributes(collected) == {}


def test_the_default_is_not_applied_to_an_empty_snapshot_at_the_resolver_either() -> None:
    """The boundary above, asserted at the layer that decides it rather than at the guard.

    ``on_start`` returns early on an empty snapshot, so the previous test would
    still pass if :func:`_scope.resolve_attributes` defaulted unconditionally —
    the early return would be doing all the work, and the next caller of the
    resolver (03-04's cap validation is already named as one) would inherit a
    resolver that manufactures a key out of nothing.
    """
    assert _scope.resolve_attributes(_scope.current()) == {}
